spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fsa
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    name: fsa
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    mapping-resources:
      - persistence/statstracker-orm.xml
  liquibase:
    change-log: classpath:persistence/db/changelog/changelog-master.xml
# Kubernetes probes (readiness & liveness) and monitoring
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/FSA
          jwk-set-uri: http://localhost:8081/realms/FSA/protocol/openid-connect/certs
